<a href="https://colab.research.google.com/github/nazmulhasan015/114/blob/main/Coloab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
C=input("celcius scale:")
C=float(C)
Far=float((C/5)*9+32)
print(f"farenhiet scale: {Far}")

celcius scale:98
farenhiet scale: 208.4


In [ ]:
Fruits= ["apple","banana","cherry"]
print(Fruits[1:3])

['banana', 'cherry']


In [ ]:
Fruits=["apple","banana","cherry","mango"]
print(Fruits)
Fruits.remove("banana")

['apple', 'banana', 'cherry', 'mango']


In [ ]:
for i in range(1,10):
  print(i)

1
3
5
7
9


In [ ]:
Fruits=["apple","banana","mango","pam","jacfruits","guava"]
print(Fruits)

['apple', 'banana', 'mango', 'pam', 'jacfruits', 'guava']


In [ ]:
fruits=["apple","banana","cherry","mango"]
print(fruits)
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)

['apple', 'banana', 'cherry', 'mango']
['apple', 'banana', 'cherry', 'mango']
['mango', 'cherry', 'banana', 'apple']


In [ ]:
fruits=["apple","banana","cherry","mango"]
myfruits=input("Enter fruit name: ")
for fruit in fruits:
  if fruit == myfruits:
    print("Your fruit is in the list...")
    break
    else:
      print("Your fruits doesn't in the list")
      break

SyntaxError: invalid syntax (<ipython-input-6-0561b34ad69e>, line 7)

In [ ]:

Name=Nazmul Hasan
print("Name")
age=("enter your age")
print("age")


SyntaxError: invalid syntax (<ipython-input-54-6a225cb4d60b>, line 1)

In [ ]:
print("Hello,Nazmul")

Hello,Nazmul


In [ ]:
Q2
a=12345
b=6789


In [ ]:
Q3
calculate=[(10+20)*30/5]
print("calculate")

NameError: name 'Q3' is not defined

In [ ]:
Q6
fruits=["apple","banana","cherry","mango"]
myfruits=input("Enter fruit name: ")
for fruit in fruits:
  if fruit == myfruits:
    print("Your fruit is in the list...")
    break
    else:
      print("Your fruits doesn't in the list")
      break

SyntaxError: invalid syntax (<ipython-input-6-320df1a648ad>, line 8)

In [ ]:
person={}
print(person)

{}


In [ ]:
person={""}
print(person)

{''}


In [ ]:
person={""}
print(person)

{''}


In [ ]:
person={"name":"Nazmul", "age":"22", "city":'Khulna'}
print(person)

TypeError: 'str' object is not callable

In [ ]:
student={"name":"Nazmul","age":22,"major":"Physics"}
for key in student:
print(key,Student[key])

IndentationError: expected an indented block after 'for' statement on line 2 (<ipython-input-2-b837e322f6bc>, line 3)

In [ ]:
C=input("celcius scale:")
C=float(C)
Far=float((C/5)*9+32)
print(f"farenhiet scale: {Far}")

celcius scale:100
farenhiet scale: 212.0


In [ ]:

print("Hello, NAZMUL!")
age=input("your age is:")

Hello, NAZMUL!
your age is:22


In [ ]:
Q2(1)
string_number="12345"
integer_number=int(string_number)
print("string to integer:", integer_number)

string to integer: 12345


In [ ]:
Q2(2)
integer_number=12345
string_number=str(integer_number)
print("integer to string:", string_number)

integer to string: 12345


In [ ]:
Q3
a=((10+20*30/5))
print(a)

130.0


In [ ]:
Q4
a=input("Enter a number")
a=int(a)
if a%2==0:
  print("Even")
else:
  print("Odd")

Enter a number6
Even


In [ ]:
Q5
c=input("Enter a number")
c=int(c)
if c>0:
  print("Positive")
elif c<0:
  print("Negative")
else:
  print("Zero")

Enter a number9
Positive


In [ ]:
Q6
Fruits=["apple","banana","mango","pam","jacfruits","guava"]
for i in Fruits:
  print(i)

apple
banana
mango
pam
jacfruits
guava


In [ ]:
Q7
a=[1,2,3,4,5,6,7,8,9,10]
a[2]=20
print(a)

[1, 2, 20, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
Q8
a=[1,2,3,4,5,6,7,8,9,10]
b=[num*2 for num in a]
print(b)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
Q9
a=(1,2,3,4,5)
sum(a)

15

In [ ]:

a=10
b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

13
7
30
3.3333333333333335
1
1000


In [ ]:
A=int(input("enter first number"))
B=int(input("inter second number"))
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A%B)
print(A**B)

enter first number14
inter second number24
38
-10
336
0.5833333333333334
14
3214199700417740936751087616


In [ ]:
A=int(input("enter first number"))
B=int(input("inter second number"))
c=int(input("enter third number"))
if A>B and A>C:
  print("Greater num:",a)
elif B>A and B>C:
  print("Greater num""b")
elif C>A and C>B:
  print("Greater num:",c)
else:
  print("C is largest")

enter first number5
inter second number7
enter third number10
Greater num: 10


In [ ]:
A=int(input("enter first number"))
B=int(input("inter second number"))
c=int(input("enter third number"))
if A>B:
  if A>C:
    print("A is largest")
  else:
    print("C is largest")
elif B>A:
  if B>C:
    print("B is largest")
  else:
    print("C is largest")

enter first number8
inter second number9
enter third number11
C is largest


In [ ]:
z=0
if z>0:
  print("z is Positive")
elif z<0:
  print("z is Negative")
else:
  print("z is Zero")

z is Zero


In [ ]:
score=float(input("Mark="))
if 90 <= score <= 100:
  grade=("A")
elif 80 <= score < 90:
  grade=("B")
elif 70 <= score < 80:
  grade=("C")
elif 60 <= score < 70:
  grade=("D")
else:
  grade='F'
print("Grade:",grade)

Mark=90
Grade: A


In [ ]:
score=float(input("Mark="))
if 90 <= score <= 100:
  grade=("A")
elif 80 <= score < 90:
  grade=("B")
elif 70 <= score < 80:
  grade=("C")
elif 60 <= score < 70:
  grade=("D")
else:
  grade='F'
  print("Grade:",grade)

In [ ]:
a=-10
if a>0:
  print(" a is positive")
  print("job done")

if a>0:
  print(" a is positive")
print("job done")

job done


In [ ]:
i=1
while i<=5:
  print(i)
  i +=1

1
2
3
4
5


In [ ]:
password="123"
while password!="secret":
  password=input("Enter password:")
print("Access granted")


Enter password:456
Enter password:secret
Access granted


In [ ]:
def add(a,b):
  return a+b
result=add(5,3)
print(result)

8


In [ ]:
evens=list(filter(lambda x:x%2==0,[1,2,3,4,5,6]))
print(evens)

[2, 4, 6]


In [ ]:
def great(name="Nazmul"):
  print("Hello",name)
great()
great("Tanni")

Hello Nazmul
Hello Tanni


In [ ]:
def add(x,y):
  return x+y
result=add(5,3)
print(result)

8


In [ ]:
def add(x,y=0):
  return x+y
z=add(5,7)
print(z)
z=add(6,8)
print(z)

12
14


In [ ]:
def add_func(*args):
  return sum(args)
print(add_func(35,62,63,58,78,45,75,485,45,47,58,47,48,45,47,65,12,66))

1381


In [ ]:
def display_info(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}: {value}")
display_info(name="Nazmul",age=22,city="Khulna")

name: Nazmul
age: 22
city: Khulna


In [ ]:
def myFun(*argv):
  print("printing using loop")
  for arg in argv:
    print(arg)
  print("printing one by one")
  print(argv[0])
  print(argv[1])
myFun('Hello', 'Welcome', 'to','GeeksforGeeks')

printing using loop
Hello
Welcome
to
GeeksforGeeks
printing one by one
Hello
Welcome


In [ ]:
def myFun(arg1, *argv):
  print("first argument :", arg1)
  for arg in argv:
    print("Next argument through *argv :", arg)
myFun('Hello', 'Welcome', 'to', 'GeeksforGeeks')

first argument : Hello
Next argument through *argv : Welcome
Next argument through *argv : to
Next argument through *argv : GeeksforGeeks


In [ ]:
def myFun(*args,**kwargs):
  print("args:", args)
  print("kwargs:", kwargs)
myFun("geeks", "for","geeks", first="geeks", mid="for", last="geeks")

args: ('geeks', 'for', 'geeks')
kwargs: {'first': 'geeks', 'mid': 'for', 'last': 'geeks'}


In [ ]:
def myFun(arg1,*args,**kwargs):
  print("This is the first argument ", arg1)
  print("args:", args)
  print("kwargs:", kwargs)
myFun("geeks", "for","geeks", first="geeks", mid="for", last="geeks")

This is the first argument  geeks
args: ('for', 'geeks')
kwargs: {'first': 'geeks', 'mid': 'for', 'last': 'geeks'}


In [ ]:
def add(a:int,b:int)->int:
  return a+b
print(add(1,3))

4


In [ ]:
def outer():#outer function
    print("Hello from outer function")
    def nested():#inner function
        print("Hello from inner function")
    nested()
# Hello from outer function
# Hello from inner function
outer()

Hello from outer function
Hello from inner function


In [ ]:
def outer():#outer function
    print("Hello from outer function")
    def nested():#inner function
        print("Hello from inner function")
    print("Hello again from outer function")
    nested()
# Hello from outer function
# Hello from inner function
outer()

Hello from outer function
Hello again from outer function
Hello from inner function


In [ ]:
txt_global= "Hello global"
def outer(msg):
  txt local="Hello" # Local variable

print(txt global) #calling a global variable
print(txt local) #calling a local variable

SyntaxError: invalid syntax (<ipython-input-61-73f54ef1d19c>, line 3)

In [ ]:
def outer(msg):
  def inner():
    print(msg)
  inner ()

outer("Hello")

Hello


In [ ]:
def outer (x):
  def inner(y):
    return x+y
  return inner

add_five = outer(5)
print(add_five(10))

15


In [ ]:
def make_multiplier_of(n):
  def multiplier(x):
    return x*n
  return multiplier
times3=make_multiplier_of(3)
times5=make_multiplier_of(5)
print(times3(9))
print(times5(3))

27
15


In [ ]:
def factorial(n):
  if n==1:
    return 1
  else:
    return n*factorial(n-1)
print(factorial(5))

120


In [ ]:
def apply_twice(func,arg):
  return func(func(arg))
def add(x):
  return x+5
print(apply_twice(add_five,10))

20


In [ ]:
fruits=['apple','banana','cherry','mango','guava']
numbers=[1,2,3,4,5]
mixed_list=[1,'apple',3.14,True]
print(fruits[0])
print(numbers[1])
print(mixed_list[2])
print(fruits[-1])
print(numbers[-3])
print(mixed_list[-1])
print(fruits[1:4])
print(numbers[:2])
print(mixed_list[1:])
print(fruits[-2:])
fruits.append('orange')
print(fruits)
fruits.insert(1,"blueberry")
print(fruits)
fruits.extend(['watermilon','lichi'])
print(fruits)
fruits.extend(numbers)
print(fruits)
print(numbers)
numbers.extend(fruits)
print(numbers)
fruits.remove('guava')
print(fruits)
fruits.pop(3)
print(fruits)
fruits_copy=fruits.copy()
print(fruits_copy)
fruits_2=fruits
fruits.append('another fruit')
print(fruits)
print(fruits_2)

apple
2
3.14
guava
3
True
['banana', 'cherry', 'mango']
[1, 2]
['apple', 3.14, True]
['mango', 'guava']
['apple', 'banana', 'cherry', 'mango', 'guava', 'orange']
['apple', 'blueberry', 'banana', 'cherry', 'mango', 'guava', 'orange']
['apple', 'blueberry', 'banana', 'cherry', 'mango', 'guava', 'orange', 'watermilon', 'lichi']
['apple', 'blueberry', 'banana', 'cherry', 'mango', 'guava', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 'apple', 'blueberry', 'banana', 'cherry', 'mango', 'guava', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5]
['apple', 'blueberry', 'banana', 'cherry', 'mango', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5]
['apple', 'blueberry', 'banana', 'mango', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5]
['apple', 'blueberry', 'banana', 'mango', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5]
['apple', 'blueberry', 'banana', 'mango', 'orange', 'watermilon', 'lichi', 1, 2, 3, 4, 5, 'another fruit']
['apple', 'blueberry', 'banana', 'man

sort dile 1st dik theke asbe r reverse dile ulto dik theke asbe

In [ ]:
factrial_list = [1,2,3,4,5]
factrial_list.reverse()
print(factrial_list)
factrial_list.sort()
print(factrial_list)
factrial_list.sort(reverse=True)
print(factrial_list)

[5, 4, 3, 2, 1]
[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


In [ ]:
def fibo(n):
  a=0
  b=1
  print(a)
  print(b)
  x=0
  while x<n:
    c=a+b
    print(c)
    a=b
    b=c
    x+=1
fibo(20)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946


In [ ]:
def fibo(n):
  a=0
  b=1
  print(a)
  print(b)
  x=0
  while x<n:
    c=a+b
    print(c)
    a=b
    b=c
    x+=1
fibo(20)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946


In [ ]:
a,b=0,1
series_lenght=20
print(a,b,end=" ")
for i in range(series_lenght):
  c=a+b
  print(c, end=" ")
  a=b
  b=c

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 

In [ ]:
  Name="Hasan"
  Age=22
  txt=f"Congrations!Mr. {Name},you are {Age} years old"
  print(txt)

Congrations!Mr. Hasan,you are 22 years old


new file open rule

In [ ]:
f=open("demofile3.txt","w+")
f.write("Woo! contents has been deleted")
print(f.read())
f.close()

In [ ]:
f=open("new_file.txt","w")
f.write("thank you, boss")
f.close()
f=open("new_file.txt","r")
print(f.read(15))
f.close()
print(" using loop............")
f=open("new_file.txt","r")
for x in f:
  print(x)
f.close()

print("deleted contents")
d=open("new_file.txt","w")
d.write("Hello, world!")
d.close()


thank you, boss
 using loop............
thank you, boss
deleted contents


In [ ]:
f=open("new_file.txt","w")
f.write("thank you, boss")
f.close()
f=open("new_file.txt","r")
print(f.read(15))
f.close()
print(" using loop............")
f=open("new_file.txt","r")
for x in f:
  print(x)
f.close()

print("file creation")
f=open("demofile4.txt","x")
f.write("Newly created file")
f.close()

thank you, boss
 using loop............
thank you, boss
file creation


In [ ]:
try:
  with open("demofile4.txt","r") as f:
    print(f.read())
except:
  print("Error")
  print("File not found")
  print("File created")
  with open("demofile4.txt","w") as f:
    f.write("Hello, world!")

Newly created file


In [ ]:
x="EDGE"
try:
  print(x)
except:
  print("An exception occurred")


EDGE


In [ ]:
def check_even_odd(num):
    if num % 2 == 0:
        return f"{num} is even."
    else:
        return f"{num} is odd."

In [ ]:
number =17
result = check_even_odd(number)
print(result)



17 is odd.


In [ ]:
n = 10
even_nums = generate_even_numbers(n)
print("Even numbers up to", n, "are:", even_nums)

NameError: name 'generate_even_numbers' is not defined

In [ ]:
n = 10
even_nums = generate_even_numbers(n)
print("Even numbers up to", n, "are:", even_nums)

Even numbers up to 10 are: [2, 4, 6, 8, 10]


In [ ]:
n=10
odd_nums=[]
for i in range(1,n+1):
  if i%2==1:
    odd_nums.append(i)
print(odd_nums)

[1, 3, 5, 7, 9]


In [ ]:
n = 10
odd_nums = generate_odd_numbers(n)
print("Odd numbers up to", n, "are:", odd_nums)

NameError: name 'generate_odd_numbers' is not defined

In [ ]:
def check_even_odd(num):
    if num % 2 == 0:
        return f"{num} is even."
    else:
        return f"{num} is odd."
number = 6
result = check_even_odd(number)
print(result)


6 is even.


even and odd

In [ ]:
print("print odd number from 1 to 10")
i=0
while i<10:
  i+=1
  if i%2==0:
    continue
  print(i)

print odd number from 1 to 10
1
3
5
7
9


In [ ]:
print("print even number from 1 to 10")
i=-1
while i<10:
  i+=1
  if i%2==1:
    continue
  print(i)

print even number from 1 to 10
0
2
4
6
8
10


In [ ]:
i = 0
n=int(input("Enter a number= "))
while i< n:
  i=i+1
  if i%2 == 0:
    continue
  print(i, end=" ")

TypeError: 'str' object is not callable

In [ ]:
for n in range(1,10):
  if n%2==0:
    continue
  print(n, end=" ")
while


SyntaxError: invalid syntax (<ipython-input-59-d761434e0bf1>, line 6)

In [ ]:
def fnReverseNumber():
  n= int(input("Enter a Number:"))
  l= len(n)
  for i in range(l):
    x = n%10
    y = int(n/10)
    print(x, end=" ")
    n = y
fnReverseNumber()

TypeError: 'str' object is not callable

In [ ]:
def fnReverseNumber():
  n= int(input("Enter a Number:"))
  l= len(n)
  for i in range(l):
    x = n%10
    y = int(n/10)
    print(x, end=" ")
    n = y
fnReverseNumber()

TypeError: 'str' object is not callable

In [ ]:
def factorial_iterative(n):
    if n < 0:
        return None  # Factorial is not defined for negative numbers
    result = 1
    for i in range(1, n + 1):
      result *= i
    return result
print(factorial_iterative(5))

120


In [ ]:
n=input( )
a,b=0,1
print(a)
for x in range(n):
  c=a+b
  print(c)
  a=b
  b=c

TypeError: 'str' object is not callable

python 3.4 er oper a install kora jai

In [ ]:
pip--version

pip 23.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)


In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[1,4,3]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [1 4 3]]


In [ ]:
arr_3d=np.array([[1,2,3],[4,5,6,],[1,2,3],[4,5,6]])
print(arr_3d)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
zeros=np.zeros((2,2,3))
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
ones=np.ones((2,2,3))
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
twos=np.full((2,2,3),2)
print(twos)

[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


In [ ]:
arrange=np.arange(0,10,2)
print(arrange)

[0 2 4 6 8]


arrange er kaj hosse ata 0 theke 10 porjonto jabe gap thakbe 2 karon last er number thakbe gap

In [ ]:
arrange=np.arange(3,20,2)
print(arrange)

[ 3  5  7  9 11 13 15 17 19]


linspace er kaj hosse vag korte hbe, last a 5 ty 10 k 5 vag a vag kora hoyese

In [ ]:
linspace=np.linspace(0,10,5)
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


arr er kaj hosse jkhn 0 dibo tkhn 1 st ta print debe r -1 mane ses er ta

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[2])
print(arr[-2])

1
5
3
4


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[1,4,3]])
print(arr_2d[0,0])
print(arr_2d[0,1])
print(arr_2d[2,2])
print(arr[2:4,])

1
2
3
[3 4]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,1])
print(arr_2d[:,0:1])
print(arr_2d[1:0])

2
[[1]
 [4]
 [7]]
[]


In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1+4,arr2-3)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[5 6 7 8 9] [3 4 5 6 7]


In [ ]:
arr1=np.array([[1,2],[3,4,]])
arr2=np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

15
3.0
3.0
1.4142135623730951


mean mane গড়, stg mane vag
sum mane jog::r

In [ ]:
arr=np.arange(1,13)
arr_reshaped=arr.reshape(3,4)
arr_reshaped_2=arr.reshape(4,3)
print(arr)
print(arr_reshaped)
print(arr_reshaped_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
print(np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))

[[1 2]
 [3 4]
 [5 6]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Excel import korte hbe
যদি A:C দেয় তবে A ধেকে C পযন্ত আসবে।

In [ ]:
import pandas as pd
from google.colab import files
uploaded=files.upload()

df_1= pd.read_excel("ABC.xlsx",sheet_name="Sheet1")

print(df_1.head())

df_2=pd.read_excel("ABC.xlsx",sheet_name="Sheet2",usecols="A,C,D")
print(df_2.head())



Missing Value
jody print(df_1.head()) dewa hoi tobe se 1st 1 ta data print diye debe


In [ ]:
mean_age=df_1["Age"].mean()
print(mean_age)

df_1["Age"]=df_1["Age"].fillna(mean_age)
print(df_1.head())

39.666666666666664
      Name        Age  Income
0    Alice  25.000000   50000
1      Bob  39.666667   30000
2  Charlie  46.000000   42000
3    Mithu  35.000000   62000
4     Akhi  75.000000   42000


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
df=df_1
#Line plot
plt.figure(figsize=(10,5))
plt.plot(df["Age"], df["Income"],color="orange",marker="o")
plt.xticks(np.arange(10, 80, step=5))
plt.title("Income vs Age ")
plt.xlabel("Age")
plt.ylabel("Income")
plt.show()


NameError: name 'df_1' is not defined

In [ ]:
#Bar chart

plt.figure(figsize=(10,5))
plt.bar(df_2["City"],df_2["Income"], color="blue")
plt.title("Amount by category")
plt.xlabel("City")
plt.ylabel("Amount")
plt.show()

NameError: name 'df_2' is not defined

<Figure size 1000x500 with 0 Axes>

In [ ]:
import pandas as pd
from google.colab import files
uploaded=files.upload()

df_1= pd.read_excel("Titanic.xlsx",sheet_name="Sheet1")

print(df_1.head())

df_2=pd.read_excel("Titanic.xlsx",sheet_name="Sheet2",usecols="A,C,D")
print(df_2.head())

In [ ]:

from google.colab import files
uploaded=files.upload()