<a href="https://colab.research.google.com/github/nazmulhasan015/114/blob/main/Numpyproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def create_arrays():
    # Create a 1D array
    array1 = np.array([1, 2, 3, 4, 5])
    print("1D Array:", array1)

    # Create a 2D array
    array2 = np.array([[1, 2, 3], [4, 5, 6]])
    print("2D Array:\n", array2)

    # Create an array with zeros
    zeros_array = np.zeros((2, 3))
    print("Array of Zeros:\n", zeros_array)

    # Create an array with ones
    ones_array = np.ones((3, 2))
    print("Array of Ones:\n", ones_array)

    # Create an array with a range of values
    range_array = np.arange(0, 10, 2)
    print("Array with Range:", range_array)

    # Create a linspace array
    linspace_array = np.linspace(0, 1, 5)
    print("Linspace Array:", linspace_array)

    # Matrix multiplication
    matrix1 = np.array([[1, 2], [3, 4]])
    matrix2 = np.array([[5, 6], [7, 8]])
    product = np.dot(matrix1, matrix2)
    print("Matrix Product:\n", product)

def main():
    print("NumPy Project")
    create_arrays()

if __name__ == "__main__":
    main()


NumPy Project
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array with Range: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Matrix Product:
 [[19 22]
 [43 50]]
